
<input type="hidden"
    name="<?= $block->escapeHtml($block->getNPrefix()) ?>"
    value="" /><!-- this is send if nothing is checked -->
<ul class="checkboxes">
    <?php foreach ($block->getValues() as $name => $label): 
        ?>
        <li>
            <input type="checkbox" value="<?= $block->escapeHtml($name) ?>"
                name="<?= $block->escapeHtml($block->getNPrefix()) ?>[]"
                id="<?= $block->escapeHtml($block->getId() . '_' . $name) ?>"
                <?= ($block->escapeHtml($block->getIsChecked($name)) ? ' checked="checked"' : '') ?> />
            <label for="<?=$block->escapeHtml($block->getId() . '_' . $name) ?>">
                <?=  $block->escapeHtml($label) ?>
            </label>
        </li>
    <?php endforeach; ?>
</ul>
