<?= $block->getButtonHtml(); ?>
<div id="featchNullSKUToMagento" style="display:none;">
    <b><h3>Using this cron job, we are fetching all images from  Acquia DAM which does not have any single images into magento product.</h3></b>
</div>
<div id="autoAddDataProduct" style="display:none;">
    <b><h3>Once any Acquia DAM user/member add the sku in selected meta propety so those assest (items) automatically sync to magento using this cron job.</h3></b>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Description',
                buttons: [{
                    text: $.mage.__('OK'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            
            var popup = modal(options, $('#featchNullSKUToMagento'));
            window.FeatchNullSKUToMagento = function() {
                $('#featchNullSKUToMagento').modal('openModal');
            };
            var popup = modal(options, $('#autoAddDataProduct'));
            window.AutoAddDataProduct = function() {
                $('#autoAddDataProduct').modal('openModal');
            };
            
            
        }  
    );
</script>
