
<div class="pp-buttons-container">
    <?= $block->getButtonHtml(); ?>
</div>

<script>
    require([
        'jquery',
        'prototype'
    ], function ($) {

        var checkbox_checked = 0;
        var sku_limit = 0;
        $('#widensyncdata_widen_sync_data_check_for_all_checkbox').change(function () {
            if ($(this).is(':checked')) {
                $("#row_widensyncdata_widen_sync_data_sku_limit").hide();
                checkbox_checked = 1;
            } else {
                $("#row_widensyncdata_widen_sync_data_sku_limit").show();
                checkbox_checked = 0;
            }

        });

        $('#get_sync_sku_button').click(function () {
            var product_sku = $('textarea#widensyncdata_widen_sync_data_sku').val();
            var select_attribute = $('select#widensyncdata_widen_sync_data_select').val();
            if (checkbox_checked == 0) {
                sku_limit = $('#widensyncdata_widen_sync_data_sku_limit').val();
            } else {
                sku_limit = 0;
            }

            var params = {
                product_sku: product_sku,
                select_attribute: select_attribute,
                sku_limit: sku_limit
            };
            new Ajax.Request('<?= $block->escapeUrl($block->getAjaxUrl()); ?>', {
                parameters: params,
                loaderArea: true,
                asynchronous: true,
                beforeSend: function () {
                    $('body').trigger('processStart');
                },
                onSuccess: function (transport) {
                    var response = JSON.parse(transport.responseText);

                    var resultText = '';
                    if (response.status == 1) {
                        resultText = response.message
                        console.log(response.message);
                        $('#widensyncdata_widen_sync_data_sku').text(resultText);
                        $(".success-msg-sync").show();
                        $(".error-msg-sync").hide();
                        $(".success-msg-sync").html("Sku Get Successfully...!");
                        setTimeout(function () { 
                            
                            $('.success-msg-sync').delay(5000).fadeOut('slow');
                        }, 5000);
                    } else {
                        resultText = transport.statusText;
                        $('#widensyncdata_widen_sync_data_sku').text('');
                        $(".success-msg-sync").hide();
                        $(".error-msg-sync").show();
                        $(".error-msg-sync").html("There is not any empty Widen Data in product.");
                        setTimeout(function () { 
                            $('.error-msg-sync').delay(5000).fadeOut('slow');
                        }, 5000);
                    }

                }
            });
        });
    });
</script>
